// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBshrd75Lqu5i18jprYE-rUEJ7M8XaypVY',
    appId: '1:1003174539294:web:89aa8b2cb92a40b0157e0f',
    messagingSenderId: '1003174539294',
    projectId: 'todoapp-a49da',
    authDomain: 'todoapp-a49da.firebaseapp.com',
    storageBucket: 'todoapp-a49da.firebasestorage.app',
    measurementId: 'G-CM53BH51ZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkOpuox5HRdUz9esHU9FdQIJ_oayg6oto',
    appId: '1:1003174539294:android:286f6f37ea4c5e37157e0f',
    messagingSenderId: '1003174539294',
    projectId: 'todoapp-a49da',
    storageBucket: 'todoapp-a49da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjYD2wJ_84xurtbD0KoeyLNsstfAJi4rw',
    appId: '1:1003174539294:ios:4d70e278bb0dbb2e157e0f',
    messagingSenderId: '1003174539294',
    projectId: 'todoapp-a49da',
    storageBucket: 'todoapp-a49da.firebasestorage.app',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjYD2wJ_84xurtbD0KoeyLNsstfAJi4rw',
    appId: '1:1003174539294:ios:4d70e278bb0dbb2e157e0f',
    messagingSenderId: '1003174539294',
    projectId: 'todoapp-a49da',
    storageBucket: 'todoapp-a49da.firebasestorage.app',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBshrd75Lqu5i18jprYE-rUEJ7M8XaypVY',
    appId: '1:1003174539294:web:3fc67cfeccbf0a8e157e0f',
    messagingSenderId: '1003174539294',
    projectId: 'todoapp-a49da',
    authDomain: 'todoapp-a49da.firebaseapp.com',
    storageBucket: 'todoapp-a49da.firebasestorage.app',
    measurementId: 'G-FCDT0ZEMR4',
  );
}
